export const AKQUISE_DEMO_LEADS: Record<string, any> = {
  "l1": {
    id: "l1", name: "BSZ Sanitär & Heizung AG", industry: "Haustechnik", city: "Zürich", score: 78, status: "Recherchiert",
    address: "Industriestrasse 15, 8005 Zürich", phone: "+41 44 271 33 44", email: "info@bsz-sanitaer.ch", website: "https://bsz-sanitaer.ch",
    googleRating: 4.3, googleReviews: 42, analyzed: true, websiteScore: 55, socialScore: 20, seoScore: 48,
    websiteAnalysis: { overall: 55, seo: 48, speed: 62, mobile: 45, content: 52,
      issues: ["Website nicht mobiloptimiert", "Keine SSL auf Unterseiten", "Referenzbilder nicht optimiert (2-4 MB)", "Keine Meta-Beschreibungen", "Kein Online-Kontaktformular für Notfälle"],
      opportunities: ["24/7 Notfall-Kontaktformular einrichten", "Referenzprojekte Vorher/Nachher showcasen", "Lokale SEO für 'Sanitär Zürich'"],
    },
    socialAnalysis: { platforms: [
      { name: "Instagram", found: false, handle: "", url: "" },
      { name: "Facebook", found: true, handle: "BSZ Sanitär", url: "https://facebook.com/bszsanitaer" },
      { name: "LinkedIn", found: false, handle: "", url: "" },
      { name: "TikTok", found: false, handle: "", url: "" },
    ], score: 20,
      issues: ["Kein Instagram-Profil", "Facebook: Letzter Post vor 4 Monaten", "Kein LinkedIn trotz B2B-Geschäft", "Keine Bewertungen aktiv gemanaged"],
      opportunities: ["LinkedIn für Architekten-Netzwerk", "Instagram für Referenzprojekte", "Google Business regelmässig bespielen"],
    },
    recommendations: [
      { title: "Website mobiloptimiert neu gestalten", description: "Responsive Redesign mit Notfall-Kontakt, Leistungsübersicht und Referenzprojekte.", impact: "hoch", effort: "aufwändig", category: "Website" },
      { title: "Google Business Profil optimieren", description: "Vollständiges Profil, Projekt-Fotos, auf alle Bewertungen antworten.", impact: "hoch", effort: "einfach", category: "Local SEO" },
      { title: "LinkedIn-Firmenprofil aufbauen", description: "Netzwerk mit Architekten, Bauherren und GU. Case Studies teilen.", impact: "hoch", effort: "mittel", category: "Social Media" },
      { title: "Lokale SEO-Strategie", description: "Keywords 'Sanitär Zürich', 'Heizungsinstallation Zürich'. Verzeichniseinträge pflegen.", impact: "hoch", effort: "mittel", category: "SEO" },
      { title: "Referenz-Portfolio digitalisieren", description: "Projekte fotografieren, mit Beschreibung und Feedback auf Website präsentieren.", impact: "mittel", effort: "mittel", category: "Content" },
      { title: "Online-Terminbuchung", description: "Beratungstermine direkt über Website buchen. Reduziert Telefonaufwand.", impact: "mittel", effort: "einfach", category: "Website" },
    ],
    aiSummary: "Die BSZ Sanitär & Heizung AG hat einen soliden Ruf mit 4.3 Sternen, aber die digitale Präsenz hinkt deutlich hinterher. Website veraltet, Social Media kaum genutzt, SEO minimal. Enormes Potenzial für mehr Anfragen durch moderne Website, Google Business und lokale SEO.",
    quickWins: ["Google Business komplett ausfüllen", "Auf alle Bewertungen antworten", "Notfall-Nummer prominent auf Website", "5 beste Referenzprojekte online stellen"],
    longTermStrategy: "Komplette digitale Neuausrichtung: Responsive Website, LinkedIn für B2B, Instagram für Projekte, konsequente lokale SEO-Strategie.",
    strengths: ["Gute Google-Bewertungen (4.3★)", "Etabliert in Zürich", "Breites Leistungsspektrum", "Website vorhanden"],
    weaknesses: ["Website nicht mobiloptimiert", "Kaum Social Media", "Kein LinkedIn trotz B2B", "SEO-Sichtbarkeit gering", "Keine Online-Terminbuchung"],
    estimatedMonthlyValue: 2200,
  },
  "l2": {
    id: "l2", name: "Pema Lüftung GmbH", industry: "Lüftungstechnik", city: "Winterthur", score: 85, status: "Neu",
    address: "Technopark 8, 8406 Winterthur", phone: "+41 52 234 56 78", email: "info@pema-lueftung.ch", website: "https://pema-lueftung.ch",
    googleRating: 4.5, googleReviews: 18, analyzed: true, websiteScore: 42, socialScore: 10, seoScore: 35,
    websiteAnalysis: { overall: 42, seo: 35, speed: 55, mobile: 38, content: 40,
      issues: ["Website wirkt veraltet (Design ca. 2018)", "Nicht responsive", "Keine HTTPS auf mehreren Seiten", "Sehr wenig Textinhalt", "Keine Referenzprojekte"],
      opportunities: ["Moderne Website für Lüftungslösungen", "Technische Fallstudien anbieten", "Energieeffizienz-Rechner als Lead-Magnet"],
    },
    socialAnalysis: { platforms: [
      { name: "Instagram", found: false, handle: "", url: "" }, { name: "Facebook", found: false, handle: "", url: "" },
      { name: "LinkedIn", found: true, handle: "Pema Lüftung", url: "https://linkedin.com/company/pema-lueftung" },
      { name: "TikTok", found: false, handle: "", url: "" },
    ], score: 10,
      issues: ["LinkedIn inaktiv", "Keine anderen Social-Media-Kanäle", "Kein Content-Marketing"],
      opportunities: ["LinkedIn für Lüftungs-Fachartikel", "YouTube für Tutorials", "Case Studies auf LinkedIn"],
    },
    recommendations: [
      { title: "Kompletter Website-Relaunch", description: "Modern, responsive, mit Lüftungslösungen und Referenzen.", impact: "hoch", effort: "aufwändig", category: "Website" },
      { title: "LinkedIn-Strategie aktivieren", description: "Fachbeiträge zu Lüftungstechnik und Minergie. Architekten-Netzwerk aufbauen.", impact: "hoch", effort: "mittel", category: "Social Media" },
      { title: "SEO für Nischen-Keywords", description: "'Lüftungsanlage Winterthur', 'Komfortlüftung Schweiz'. Wenig Konkurrenz.", impact: "hoch", effort: "mittel", category: "SEO" },
    ],
    aiSummary: "Pema Lüftung hat enormes ungenutztes Potenzial. Als Spezialist in einer Nische mit wenig digitalem Wettbewerb können sie schnell zur regionalen Referenz werden. Website veraltet, Social Media inexistent. Gerade bei Energieeffizienz und Minergie gibt es starkes Suchvolumen.",
    quickWins: ["LinkedIn reaktivieren", "Google Business anlegen", "3 Referenzprojekte online stellen"],
    longTermStrategy: "Digitaler Vorreiter in der Lüftungsbranche werden. Fachcontent, Webinare, moderner Online-Auftritt.",
    strengths: ["Exzellente Bewertung (4.5★)", "Spezialisierter Nischenanbieter", "LinkedIn vorhanden"],
    weaknesses: ["Website komplett veraltet", "Social Media inexistent", "SEO nahe Null", "Nur 18 Bewertungen"],
    estimatedMonthlyValue: 2800,
  },
  "l3": {
    id: "l3", name: "Sui Innova GmbH", industry: "Gebäudetechnik", city: "Bern", score: 72, status: "Neu",
    address: "Könizstrasse 45, 3008 Bern", phone: "+41 31 398 22 11", email: "info@sui-innova.ch", website: "https://sui-innova.ch",
    googleRating: 4.1, googleReviews: 8, analyzed: true, websiteScore: 60, socialScore: 15, seoScore: 52,
    websiteAnalysis: { overall: 60, seo: 52, speed: 68, mobile: 55, content: 58,
      issues: ["Wenig Textinhalt", "Keine Blog-Sektion", "Kontaktseite schwer zu finden", "Bilder ohne Alt-Texte"],
      opportunities: ["Blog über innovative Gebäudetechnik", "Fallstudien mit messbaren Ergebnissen", "FAQ-Sektion"],
    },
    socialAnalysis: { platforms: [
      { name: "Instagram", found: false, handle: "", url: "" }, { name: "Facebook", found: false, handle: "", url: "" },
      { name: "LinkedIn", found: true, handle: "Sui Innova", url: "https://linkedin.com/company/sui-innova" },
      { name: "TikTok", found: false, handle: "", url: "" },
    ], score: 15,
      issues: ["LinkedIn minimal", "Keine anderen Kanäle", "Keine Mitarbeiter verknüpft"],
      opportunities: ["LinkedIn als B2B-Hauptkanal", "Innovationsprojekte dokumentieren", "Zertifizierungen hervorheben"],
    },
    recommendations: [
      { title: "Content-Marketing starten", description: "Blog zu innovativer Gebäudetechnik und Smart-Home. Positionierung als Innovationsführer.", impact: "hoch", effort: "mittel", category: "Content" },
      { title: "LinkedIn intensivieren", description: "Wöchentliche Posts zu Innovationsprojekten und Trends.", impact: "hoch", effort: "mittel", category: "Social Media" },
      { title: "SEO Bern", description: "'Gebäudetechnik Bern', 'Smart Building Bern'.", impact: "mittel", effort: "einfach", category: "SEO" },
    ],
    aiSummary: "Sui Innova positioniert sich als innovativ, nutzt digitale Kanäle aber kaum. Der Name 'Innova' verspricht Innovation - die muss auch online sichtbar werden.",
    quickWins: ["LinkedIn mit Projektbildern aktualisieren", "Google Business optimieren", "Alt-Texte ergänzen"],
    longTermStrategy: "Thought Leader für innovative Gebäudetechnik in Bern. Fachbeiträge und LinkedIn-Präsenz.",
    strengths: ["Innovativer Markenname", "Website vorhanden", "LinkedIn angelegt"],
    weaknesses: ["Sehr wenige Bewertungen (8)", "Social Media kaum aktiv", "Content fehlt", "Innovation online nicht sichtbar"],
    estimatedMonthlyValue: 1900,
  },
  "l4": {
    id: "l4", name: "Sada AG", industry: "Haustechnik", city: "Luzern", score: 65, status: "Recherchiert",
    address: "Obergrundstrasse 120, 6005 Luzern", phone: "+41 41 310 55 66", email: "info@sada.ch", website: "https://sada.ch",
    googleRating: 4.6, googleReviews: 67, analyzed: true, websiteScore: 70, socialScore: 25, seoScore: 62,
    websiteAnalysis: { overall: 70, seo: 62, speed: 75, mobile: 68, content: 72,
      issues: ["Keine strukturierten Daten", "News veraltet", "Mobile >3s", "Kein FAQ"],
      opportunities: ["Performance optimieren", "Projekte publizieren", "Testimonials einbinden"],
    },
    socialAnalysis: { platforms: [
      { name: "Instagram", found: false, handle: "", url: "" },
      { name: "Facebook", found: true, handle: "Sada AG", url: "https://facebook.com/sadaag" },
      { name: "LinkedIn", found: true, handle: "Sada AG", url: "https://linkedin.com/company/sada-ag" },
      { name: "TikTok", found: false, handle: "", url: "" },
    ], score: 25,
      issues: ["Facebook unregelmässig", "LinkedIn wenig Follower", "Kein Instagram"],
      opportunities: ["Instagram für Baustellen", "LinkedIn für Recruiting", "Facebook-Ads lokal"],
    },
    recommendations: [
      { title: "Google-Bewertungen managen", description: "4.6★ bei 67 Reviews ist stark. Systematisch nach Bewertungen fragen.", impact: "hoch", effort: "einfach", category: "Local SEO" },
      { title: "Instagram starten", description: "Visuelles Portfolio: Baustellen, fertige Projekte, Team.", impact: "mittel", effort: "mittel", category: "Social Media" },
      { title: "Website-Content aktualisieren", description: "News reaktivieren, Projekte zeigen, Kundenstimmen.", impact: "mittel", effort: "einfach", category: "Content" },
    ],
    aiSummary: "Sada AG hat mit 4.6★ und 67 Bewertungen eine der besten Reputationen. Diese starke Basis wird digital kaum genutzt. Mit wenig Aufwand grosser Effekt möglich.",
    quickWins: ["Alle Bewertungen beantworten", "LinkedIn aktualisieren", "3 Referenzprojekte publizieren"],
    longTermStrategy: "Starke Reputation digital sichtbar machen. Konsistenter Online-Auftritt mit regelmässigen Inhalten.",
    strengths: ["Hervorragende Bewertung (4.6★/67)", "Solide Website", "FB und LinkedIn vorhanden", "Etabliert in Luzern"],
    weaknesses: ["Social Media unregelmässig", "Kein Instagram", "News veraltet", "Bewertungs-Potenzial ungenutzt"],
    estimatedMonthlyValue: 1600,
  },
  "l5": {
    id: "l5", name: "Neukom Marzolo AG", industry: "Sanitär & Heizung", city: "St. Gallen", score: 81, status: "Neu",
    address: "Rorschacher Strasse 150, 9006 St. Gallen", phone: "+41 71 245 33 22", email: "info@neukom-marzolo.ch", website: "https://neukom-marzolo.ch",
    googleRating: 4.4, googleReviews: 35, analyzed: true, websiteScore: 48, socialScore: 12, seoScore: 40,
    websiteAnalysis: { overall: 48, seo: 40, speed: 52, mobile: 42, content: 48,
      issues: ["Website nicht mobiloptimiert", "Veraltetes Design", "Ladezeit >5s", "Kontaktformular defekt auf Mobile"],
      opportunities: ["Relaunch mit modernem Design", "Referenzgalerie Bäder-Renovationen", "Online-Offertanfrage"],
    },
    socialAnalysis: { platforms: [
      { name: "Instagram", found: false, handle: "", url: "" },
      { name: "Facebook", found: true, handle: "Neukom Marzolo", url: "https://facebook.com/neukommarzolo" },
      { name: "LinkedIn", found: false, handle: "", url: "" },
      { name: "TikTok", found: false, handle: "", url: "" },
    ], score: 12,
      issues: ["Nur Facebook, selten aktiv", "Kein LinkedIn", "Keine Projekt-Dokumentation"],
      opportunities: ["Instagram ideal für Bäder-Renovationen (Vorher/Nachher)", "LinkedIn für Architekten", "YouTube für Tipps"],
    },
    recommendations: [
      { title: "Website-Relaunch mit Bäder-Portfolio", description: "Grossflächige Projektbilder, insbesondere Bäder. Offertanfrage-Formular.", impact: "hoch", effort: "aufwändig", category: "Website" },
      { title: "Instagram für Badezimmer", description: "Vorher/Nachher-Content. Hohe Engagement-Raten, zeigt Kompetenz.", impact: "hoch", effort: "mittel", category: "Social Media" },
      { title: "Lokale SEO St. Gallen", description: "'Sanitär St. Gallen', 'Badezimmer Renovation'. Wenig digitale Konkurrenz.", impact: "hoch", effort: "mittel", category: "SEO" },
    ],
    aiSummary: "Neukom Marzolo hat als Sanitärbetrieb enormes digitales Potenzial. Badezimmer-Renovationen sind visuell stark und funktionieren auf Instagram extrem gut. Aktuelle Online-Präsenz minimal - mit modernem Auftritt deutlicher Wettbewerbsvorteil.",
    quickWins: ["Google Business ausfüllen", "5 Bäder-Projekte fotografieren", "Facebook aktualisieren"],
    longTermStrategy: "Premium-Anbieter für Bäder in der Ostschweiz werden. Visueller Content und hochwertige Website.",
    strengths: ["Gute Bewertung (4.4★)", "Visuell starkes Produkt", "Etabliert in St. Gallen"],
    weaknesses: ["Website stark veraltet", "Social Media inexistent", "SEO nicht vorhanden", "Potenzial komplett ungenutzt"],
    estimatedMonthlyValue: 2500,
  },
  "l6": {
    id: "l6", name: "SHS Haustechnik AG", industry: "Haustechnik", city: "Basel", score: 74, status: "Angeschrieben",
    address: "St. Jakobs-Strasse 85, 4052 Basel", phone: "+41 61 311 88 99", email: "info@shs-haustechnik.ch", website: "https://shs-haustechnik.ch",
    googleRating: 4.2, googleReviews: 29, analyzed: true, websiteScore: 58, socialScore: 18, seoScore: 50,
    websiteAnalysis: { overall: 58, seo: 50, speed: 65, mobile: 52, content: 55,
      issues: ["Mobile nicht optimal", "Keine HTTPS teilweise", "Bilder nicht komprimiert", "Fehlende H1-Tags"],
      opportunities: ["Mobile-First Redesign", "Referenzen mit Kundenstimmen", "Blog über Wärmepumpe/Solar"],
    },
    socialAnalysis: { platforms: [
      { name: "Instagram", found: false, handle: "", url: "" },
      { name: "Facebook", found: true, handle: "SHS Haustechnik", url: "https://facebook.com/shshaustechnik" },
      { name: "LinkedIn", found: true, handle: "SHS Haustechnik AG", url: "https://linkedin.com/company/shs-haustechnik" },
      { name: "TikTok", found: false, handle: "", url: "" },
    ], score: 18,
      issues: ["Facebook letzter Post vor 2 Monaten", "LinkedIn nur 45 Follower", "Kein Content-Plan"],
      opportunities: ["LinkedIn für Recruiting", "Energiewende-Themen als Content", "Instagram für Projekte"],
    },
    recommendations: [
      { title: "Energiewende als Content-Thema", description: "Blog und Social zu Wärmepumpen, Solar. Aktuelles Thema mit hohem Suchvolumen.", impact: "hoch", effort: "mittel", category: "Content" },
      { title: "LinkedIn für Recruiting/B2B", description: "Stellenangebote, Projekt-Updates, Fachbeiträge. Fachkräftemangel nutzen.", impact: "hoch", effort: "mittel", category: "Social Media" },
      { title: "Lokale SEO Basel", description: "'Wärmepumpe Basel', 'Heizung ersetzen Basel'. Google Business zentral.", impact: "hoch", effort: "einfach", category: "SEO" },
    ],
    aiSummary: "SHS Haustechnik hat eine ordentliche Basis, nutzt sie aber nicht konsequent. Energiewende bietet enormes Content-Potenzial. SHS könnte sich als Energiewende-Partner in Basel positionieren.",
    quickWins: ["Google Business mit Wärmepumpe/Solar ergänzen", "LinkedIn mit Projekt-Update bespielen", "Kontaktformular optimieren"],
    longTermStrategy: "Positionierung als Energiewende-Partner in Basel. Content rund um erneuerbare Energien und Heizungsmodernisierung.",
    strengths: ["Gute Bewertung (4.2★)", "FB und LinkedIn vorhanden", "Relevantes Thema Energiewende", "Basel = hohe Kaufkraft"],
    weaknesses: ["Social Media inaktiv", "Website nicht mobiloptimiert", "Content-Strategie fehlt"],
    estimatedMonthlyValue: 2100,
  },
  "l7": {
    id: "l7", name: "Ritschard Gebäudetechnik AG", industry: "Gebäudetechnik", city: "Thun", score: 69, status: "Recherchiert",
    address: "Allmendstrasse 22, 3600 Thun", phone: "+41 33 222 44 55", email: "info@ritschard-gebaeudetechnik.ch", website: "https://ritschard-gebaeudetechnik.ch",
    googleRating: 4.7, googleReviews: 53, analyzed: true, websiteScore: 65, socialScore: 22, seoScore: 58,
    websiteAnalysis: { overall: 65, seo: 58, speed: 70, mobile: 62, content: 65,
      issues: ["Keine Blog-Sektion", "Referenzen ohne Details", "Kontaktformular zu einfach", "Kein FAQ"],
      opportunities: ["Blog über Gebäudetechnik", "Detaillierte Referenzen mit Kennzahlen", "Video-Testimonials"],
    },
    socialAnalysis: { platforms: [
      { name: "Instagram", found: false, handle: "", url: "" },
      { name: "Facebook", found: true, handle: "Ritschard GT", url: "https://facebook.com/ritschardgt" },
      { name: "LinkedIn", found: true, handle: "Ritschard Gebäudetechnik", url: "https://linkedin.com/company/ritschard-gebaeudetechnik" },
      { name: "TikTok", found: false, handle: "", url: "" },
    ], score: 22,
      issues: ["Facebook unregelmässig", "LinkedIn minimal", "Keine Videos", "Kein Instagram"],
      opportunities: ["Instagram für Baustellen-Zeitraffer", "LinkedIn für Berner Oberland Netzwerk", "YouTube Erklärvideos"],
    },
    recommendations: [
      { title: "Top-Reputation digital nutzen", description: "4.7★ ist herausragend. Testimonials auf Website, Social Proof überall, aktiv Bewertungen sammeln.", impact: "hoch", effort: "einfach", category: "Reputation" },
      { title: "Referenzen ausbauen", description: "Detaillierte Projektbeschreibungen: Aufgabe, Lösung, Ergebnis, Kundenstimme.", impact: "hoch", effort: "mittel", category: "Content" },
      { title: "Regionale Dominanz Berner Oberland", description: "'Gebäudetechnik Thun', 'Haustechnik Berner Oberland'. Minimal digitale Konkurrenz.", impact: "hoch", effort: "mittel", category: "SEO" },
      { title: "Employer Branding", description: "Mitarbeiter-Portraits, Lehrstellen, Team-Events. Hilft bei Fachkräftegewinnung.", impact: "mittel", effort: "einfach", category: "Recruiting" },
    ],
    aiSummary: "Ritschard hat mit 4.7★ die beste Reputation aller Leads. Im Berner Oberland gibt es wenig digitale Konkurrenz - wer zuerst aktiv wird, dominiert. Top-Bewertungen + gezieltes Online-Marketing = unangefochtene Nr. 1 in der Region.",
    quickWins: ["Beste Bewertungen als Zitate auf Website", "Google Business mit allen Leistungen", "LinkedIn mit Teamfoto ergänzen"],
    longTermStrategy: "Stärkste digitale Präsenz aller Gebäudetechnik-Unternehmen im Berner Oberland. Reputation als Fundament, Content-Marketing als Treiber.",
    strengths: ["Beste Bewertung (4.7★/53)", "Solide Website", "Etabliert in Thun", "FB und LinkedIn vorhanden"],
    weaknesses: ["Top-Reputation digital ungenutzt", "Referenzen ohne Details", "Social Media unregelmässig", "Kein Instagram"],
    estimatedMonthlyValue: 1800,
  },
}
