import { type NextRequest } from "next/server"
import { auth } from "@/lib/auth"
import { prisma } from "@/lib/prisma"

const DEMO_LEADS = [
  {
    id: "demo-lead-01",
    name: "Ristorante Bellavista",
    industry: "Gastronomie",
    website: "https://bellavista-zh.ch",
    phone: "+41 44 123 45 67",
    email: "info@bellavista-zh.ch",
    address: "Limmatstrasse 42",
    city: "Zürich",
    zip: "8005",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_01",
    googleRating: 4.5,
    googleReviews: 187,
    socialMedia: { instagram: "@bellavista_zh", facebook: "bellavistazh", followers: 2300 },
    status: "RECHERCHIERT",
    score: 88,
    analysis: { websiteQuality: "gut", socialPresence: "mittel", seoScore: 72, loadTime: 1.8, mobileOptimized: true, hasOnlineBooking: false },
    recommendations: [
      "Online-Reservierungssystem einführen",
      "Instagram-Präsenz ausbauen (aktuell nur 2300 Follower)",
      "Google My Business Beiträge regelmässig veröffentlichen",
    ],
    websiteScore: 72,
    socialScore: 55,
    seoScore: 68,
    potentialValue: "CHF 1'200/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T14:30:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T14:30:00.000Z",
  },
  {
    id: "demo-lead-02",
    name: "CrossFit Bern",
    industry: "Fitness",
    website: "https://crossfit-bern.ch",
    phone: "+41 31 987 65 43",
    email: "kontakt@crossfit-bern.ch",
    address: "Bundesgasse 18",
    city: "Bern",
    zip: "3011",
    canton: "BE",
    googlePlaceId: "ChIJ_demo_02",
    googleRating: 4.8,
    googleReviews: 312,
    socialMedia: { instagram: "@crossfitbern", facebook: "crossfitbern", tiktok: "@cfbern", followers: 5800 },
    status: "RECHERCHIERT",
    score: 92,
    analysis: { websiteQuality: "sehr gut", socialPresence: "stark", seoScore: 85, loadTime: 1.2, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "TikTok-Content-Strategie entwickeln",
      "Testimonial-Videos für Website erstellen",
      "SEO für lokale Suchbegriffe optimieren",
    ],
    websiteScore: 85,
    socialScore: 78,
    seoScore: 82,
    potentialValue: "CHF 1'800/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T15:00:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T15:00:00.000Z",
  },
  {
    id: "demo-lead-03",
    name: "Modehaus Schneider",
    industry: "Mode",
    website: "https://modehaus-schneider.ch",
    phone: "+41 61 234 56 78",
    email: "info@modehaus-schneider.ch",
    address: "Freie Strasse 55",
    city: "Basel",
    zip: "4001",
    canton: "BS",
    googlePlaceId: "ChIJ_demo_03",
    googleRating: 4.2,
    googleReviews: 94,
    socialMedia: { instagram: "@modehaus_schneider", followers: 1200 },
    status: "NEU",
    score: 71,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-21",
    analyzedAt: null,
    createdAt: "2026-05-21T08:00:00.000Z",
    updatedAt: "2026-05-21T08:00:00.000Z",
  },
  {
    id: "demo-lead-04",
    name: "Immobilien Zentralschweiz AG",
    industry: "Immobilien",
    website: "https://immo-zentralschweiz.ch",
    phone: "+41 41 345 67 89",
    email: "office@immo-zentralschweiz.ch",
    address: "Pilatusstrasse 22",
    city: "Luzern",
    zip: "6003",
    canton: "LU",
    googlePlaceId: "ChIJ_demo_04",
    googleRating: 4.1,
    googleReviews: 56,
    socialMedia: { linkedin: "immobilien-zentralschweiz", facebook: "immozentralschweiz", followers: 890 },
    status: "ANGESCHRIEBEN",
    score: 65,
    analysis: { websiteQuality: "mittel", socialPresence: "schwach", seoScore: 58, loadTime: 3.2, mobileOptimized: false, hasOnlineBooking: false },
    recommendations: [
      "Website dringend für Mobile optimieren",
      "Ladezeit verbessern (aktuell 3.2s)",
      "Social-Media-Strategie aufbauen",
      "Virtuelle Rundgänge auf Website integrieren",
    ],
    websiteScore: 45,
    socialScore: 32,
    seoScore: 58,
    potentialValue: "CHF 2'500/Mt",
    searchBatch: "batch-2026-05-19",
    analyzedAt: "2026-05-19T16:00:00.000Z",
    createdAt: "2026-05-19T09:00:00.000Z",
    updatedAt: "2026-05-21T11:00:00.000Z",
  },
  {
    id: "demo-lead-05",
    name: "Praxis Dr. Meier - Physiotherapie",
    industry: "Gesundheit",
    website: "https://physio-meier.ch",
    phone: "+41 52 456 78 90",
    email: "praxis@physio-meier.ch",
    address: "Marktgasse 14",
    city: "Winterthur",
    zip: "8400",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_05",
    googleRating: 4.7,
    googleReviews: 243,
    socialMedia: { instagram: "@physio_meier", facebook: "praxismeier", followers: 1650 },
    status: "RECHERCHIERT",
    score: 79,
    analysis: { websiteQuality: "gut", socialPresence: "mittel", seoScore: 75, loadTime: 2.1, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "Blog mit Gesundheitstipps starten",
      "Instagram Reels mit Übungsanleitungen",
      "Google Bewertungen aktiv einfordern",
    ],
    websiteScore: 76,
    socialScore: 52,
    seoScore: 75,
    potentialValue: "CHF 900/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T13:00:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T13:00:00.000Z",
  },
  {
    id: "demo-lead-06",
    name: "Schreinerei Hofmann & Söhne",
    industry: "Handwerk",
    website: "https://schreinerei-hofmann.ch",
    phone: "+41 44 567 89 01",
    email: "info@schreinerei-hofmann.ch",
    address: "Industriestrasse 8",
    city: "Zürich",
    zip: "8037",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_06",
    googleRating: 4.9,
    googleReviews: 78,
    socialMedia: { instagram: "@schreinerei_hofmann", followers: 540 },
    status: "NEU",
    score: 83,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
  {
    id: "demo-lead-07",
    name: "Bildungszentrum Lingua",
    industry: "Bildung",
    website: "https://lingua-sprachschule.ch",
    phone: "+41 71 678 90 12",
    email: "info@lingua-sprachschule.ch",
    address: "Bahnhofstrasse 31",
    city: "St. Gallen",
    zip: "9000",
    canton: "SG",
    googlePlaceId: "ChIJ_demo_07",
    googleRating: 4.3,
    googleReviews: 165,
    socialMedia: { instagram: "@lingua_sg", facebook: "linguastgallen", linkedin: "lingua-sprachschule", followers: 3200 },
    status: "RECHERCHIERT",
    score: 74,
    analysis: { websiteQuality: "mittel", socialPresence: "gut", seoScore: 64, loadTime: 2.5, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "SEO für Sprachkurs-Keywords verbessern",
      "YouTube-Kanal mit Lernvideos starten",
      "E-Mail-Marketing für Kursangebote",
    ],
    websiteScore: 62,
    socialScore: 71,
    seoScore: 64,
    potentialValue: "CHF 1'500/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T16:30:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T16:30:00.000Z",
  },
  {
    id: "demo-lead-08",
    name: "TechHub Zürich GmbH",
    industry: "IT",
    website: "https://techhub-zh.ch",
    phone: "+41 44 789 01 23",
    email: "hello@techhub-zh.ch",
    address: "Hardturmstrasse 120",
    city: "Zürich",
    zip: "8005",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_08",
    googleRating: 4.6,
    googleReviews: 42,
    socialMedia: { linkedin: "techhub-zurich", twitter: "@techhub_zh", github: "techhub-zh", followers: 4100 },
    status: "ANTWORT",
    score: 91,
    analysis: { websiteQuality: "sehr gut", socialPresence: "stark", seoScore: 88, loadTime: 0.9, mobileOptimized: true, hasOnlineBooking: false },
    recommendations: [
      "Case Studies prominent auf Website platzieren",
      "Regelmässige LinkedIn-Artikel publizieren",
      "Webinare als Lead-Magnete einsetzen",
    ],
    websiteScore: 90,
    socialScore: 85,
    seoScore: 88,
    potentialValue: "CHF 3'000/Mt",
    searchBatch: "batch-2026-05-18",
    analyzedAt: "2026-05-18T14:00:00.000Z",
    createdAt: "2026-05-18T10:00:00.000Z",
    updatedAt: "2026-05-21T09:00:00.000Z",
  },
  {
    id: "demo-lead-09",
    name: "Bäckerei Confiserie Stocker",
    industry: "Gastronomie",
    website: "https://baeckerei-stocker.ch",
    phone: "+41 31 890 12 34",
    email: "bestellung@baeckerei-stocker.ch",
    address: "Kramgasse 7",
    city: "Bern",
    zip: "3011",
    canton: "BE",
    googlePlaceId: "ChIJ_demo_09",
    googleRating: 4.4,
    googleReviews: 298,
    socialMedia: { instagram: "@stocker_bern", facebook: "baeckereistocker", followers: 3700 },
    status: "NEU",
    score: 77,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
  {
    id: "demo-lead-10",
    name: "Yoga Studio Innere Ruhe",
    industry: "Fitness",
    website: "https://innere-ruhe.ch",
    phone: "+41 61 901 23 45",
    email: "namaste@innere-ruhe.ch",
    address: "Spalenvorstadt 12",
    city: "Basel",
    zip: "4051",
    canton: "BS",
    googlePlaceId: "ChIJ_demo_10",
    googleRating: 4.8,
    googleReviews: 156,
    socialMedia: { instagram: "@innereruhe_yoga", youtube: "InnerRuheYoga", followers: 6200 },
    status: "RECHERCHIERT",
    score: 86,
    analysis: { websiteQuality: "gut", socialPresence: "stark", seoScore: 71, loadTime: 1.5, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "SEO-Optimierung für lokale Yoga-Suchbegriffe",
      "YouTube Shorts mit Yoga-Übungen",
      "Newsletter für Kurs-Updates und Wellness-Tipps",
    ],
    websiteScore: 74,
    socialScore: 82,
    seoScore: 71,
    potentialValue: "CHF 800/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T11:00:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T11:00:00.000Z",
  },
  {
    id: "demo-lead-11",
    name: "Autohaus Müller AG",
    industry: "Handwerk",
    website: "https://autohaus-mueller.ch",
    phone: "+41 41 012 34 56",
    email: "verkauf@autohaus-mueller.ch",
    address: "Luzernerstrasse 88",
    city: "Luzern",
    zip: "6006",
    canton: "LU",
    googlePlaceId: "ChIJ_demo_11",
    googleRating: 3.9,
    googleReviews: 134,
    socialMedia: { facebook: "autohausmueller", followers: 780 },
    status: "NEU",
    score: 52,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
  {
    id: "demo-lead-12",
    name: "Coiffure Elegance",
    industry: "Gesundheit",
    website: "https://coiffure-elegance.ch",
    phone: "+41 52 123 45 67",
    email: "termin@coiffure-elegance.ch",
    address: "Technikumstrasse 3",
    city: "Winterthur",
    zip: "8400",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_12",
    googleRating: 4.6,
    googleReviews: 211,
    socialMedia: { instagram: "@coiffure_elegance", tiktok: "@elegance_hair", followers: 4500 },
    status: "RECHERCHIERT",
    score: 81,
    analysis: { websiteQuality: "gut", socialPresence: "gut", seoScore: 66, loadTime: 2.0, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "Vorher/Nachher-Galerie auf Website",
      "TikTok-Tutorials regelmässig posten",
      "Google Bewertungen gezielt steigern",
    ],
    websiteScore: 70,
    socialScore: 76,
    seoScore: 66,
    potentialValue: "CHF 700/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T12:00:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T12:00:00.000Z",
  },
  {
    id: "demo-lead-13",
    name: "Hotel & Restaurant Alpenhof",
    industry: "Gastronomie",
    website: "https://alpenhof-luzern.ch",
    phone: "+41 41 234 56 78",
    email: "reservation@alpenhof-luzern.ch",
    address: "Seestrasse 15",
    city: "Luzern",
    zip: "6004",
    canton: "LU",
    googlePlaceId: "ChIJ_demo_13",
    googleRating: 4.3,
    googleReviews: 521,
    socialMedia: { instagram: "@alpenhof_luzern", facebook: "alpenhof.luzern", tripadvisor: true, followers: 7800 },
    status: "ANGESCHRIEBEN",
    score: 85,
    analysis: { websiteQuality: "gut", socialPresence: "stark", seoScore: 77, loadTime: 2.3, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "Mehrsprachige Website (EN, FR) für Touristen",
      "Instagram Stories mit Tagesmenüs",
      "TripAdvisor-Bewertungen aktiv managen",
    ],
    websiteScore: 73,
    socialScore: 80,
    seoScore: 77,
    potentialValue: "CHF 2'000/Mt",
    searchBatch: "batch-2026-05-18",
    analyzedAt: "2026-05-18T15:00:00.000Z",
    createdAt: "2026-05-18T10:00:00.000Z",
    updatedAt: "2026-05-21T14:00:00.000Z",
  },
  {
    id: "demo-lead-14",
    name: "IT Solutions Biel GmbH",
    industry: "IT",
    website: "https://it-solutions-biel.ch",
    phone: "+41 32 345 67 89",
    email: "info@it-solutions-biel.ch",
    address: "Zentralstrasse 44",
    city: "Biel",
    zip: "2502",
    canton: "BE",
    googlePlaceId: "ChIJ_demo_14",
    googleRating: 4.0,
    googleReviews: 28,
    socialMedia: { linkedin: "it-solutions-biel", followers: 620 },
    status: "NEU",
    score: 58,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
  {
    id: "demo-lead-15",
    name: "FitFactory Winterthur",
    industry: "Fitness",
    website: "https://fitfactory-winterthur.ch",
    phone: "+41 52 456 78 90",
    email: "info@fitfactory-winterthur.ch",
    address: "Tösstalstrasse 26",
    city: "Winterthur",
    zip: "8400",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_15",
    googleRating: 4.4,
    googleReviews: 189,
    socialMedia: { instagram: "@fitfactory_winti", facebook: "fitfactorywinterthur", followers: 3400 },
    status: "RECHERCHIERT",
    score: 76,
    analysis: { websiteQuality: "mittel", socialPresence: "gut", seoScore: 60, loadTime: 2.8, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "Website-Ladezeit optimieren",
      "Mitglieder-Testimonials einbinden",
      "Lokales SEO für Winterthur verbessern",
    ],
    websiteScore: 58,
    socialScore: 68,
    seoScore: 60,
    potentialValue: "CHF 1'100/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T14:00:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T14:00:00.000Z",
  },
  {
    id: "demo-lead-16",
    name: "Malergeschäft Brunner",
    industry: "Handwerk",
    website: "https://maler-brunner.ch",
    phone: "+41 44 567 89 01",
    email: "anfrage@maler-brunner.ch",
    address: "Birmensdorferstrasse 155",
    city: "Zürich",
    zip: "8003",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_16",
    googleRating: 4.7,
    googleReviews: 67,
    socialMedia: null,
    status: "NEU",
    score: 45,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
  {
    id: "demo-lead-17",
    name: "Boutique La Maison",
    industry: "Mode",
    website: "https://lamaison-mode.ch",
    phone: "+41 31 678 90 12",
    email: "shop@lamaison-mode.ch",
    address: "Spitalgasse 28",
    city: "Bern",
    zip: "3011",
    canton: "BE",
    googlePlaceId: "ChIJ_demo_17",
    googleRating: 4.5,
    googleReviews: 112,
    socialMedia: { instagram: "@lamaison_bern", pinterest: "lamaisonbern", followers: 5100 },
    status: "RECHERCHIERT",
    score: 82,
    analysis: { websiteQuality: "gut", socialPresence: "gut", seoScore: 70, loadTime: 1.7, mobileOptimized: true, hasOnlineBooking: false },
    recommendations: [
      "Online-Shop aufbauen",
      "Pinterest-Strategie für Mode-Content",
      "Influencer-Kooperationen in der Region Bern",
    ],
    websiteScore: 71,
    socialScore: 74,
    seoScore: 70,
    potentialValue: "CHF 1'400/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T15:30:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T15:30:00.000Z",
  },
  {
    id: "demo-lead-18",
    name: "Zahnarztpraxis am Rhein",
    industry: "Gesundheit",
    website: "https://zahnarzt-am-rhein.ch",
    phone: "+41 61 789 01 23",
    email: "praxis@zahnarzt-am-rhein.ch",
    address: "Rheingasse 10",
    city: "Basel",
    zip: "4058",
    canton: "BS",
    googlePlaceId: "ChIJ_demo_18",
    googleRating: 4.1,
    googleReviews: 89,
    socialMedia: { facebook: "zahnarztamrhein", followers: 430 },
    status: "NEU",
    score: 61,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
  {
    id: "demo-lead-19",
    name: "Nachhilfe-Institut Lernwelt",
    industry: "Bildung",
    website: "https://lernwelt-nachhilfe.ch",
    phone: "+41 71 890 12 34",
    email: "anmeldung@lernwelt-nachhilfe.ch",
    address: "Multergasse 6",
    city: "St. Gallen",
    zip: "9000",
    canton: "SG",
    googlePlaceId: "ChIJ_demo_19",
    googleRating: 4.6,
    googleReviews: 73,
    socialMedia: { instagram: "@lernwelt_sg", facebook: "lernweltnachhilfe", followers: 1900 },
    status: "RECHERCHIERT",
    score: 69,
    analysis: { websiteQuality: "mittel", socialPresence: "mittel", seoScore: 55, loadTime: 2.4, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "Blog mit Lerntipps für Eltern und Schüler",
      "Google Ads für lokale Nachhilfe-Keywords",
      "Erfolgsgeschichten auf Social Media teilen",
    ],
    websiteScore: 60,
    socialScore: 55,
    seoScore: 55,
    potentialValue: "CHF 600/Mt",
    searchBatch: "batch-2026-05-20",
    analyzedAt: "2026-05-20T16:00:00.000Z",
    createdAt: "2026-05-20T10:00:00.000Z",
    updatedAt: "2026-05-20T16:00:00.000Z",
  },
  {
    id: "demo-lead-20",
    name: "Elektro Keller GmbH",
    industry: "Handwerk",
    website: "https://elektro-keller.ch",
    phone: "+41 44 901 23 45",
    email: "info@elektro-keller.ch",
    address: "Andreasstrasse 50",
    city: "Zürich",
    zip: "8050",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_20",
    googleRating: 3.8,
    googleReviews: 41,
    socialMedia: null,
    status: "NEU",
    score: 38,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
  {
    id: "demo-lead-21",
    name: "Trattoria del Sole",
    industry: "Gastronomie",
    website: "https://trattoria-del-sole.ch",
    phone: "+41 52 012 34 56",
    email: "reservieren@trattoria-del-sole.ch",
    address: "Steinberggasse 22",
    city: "Winterthur",
    zip: "8400",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_21",
    googleRating: 4.6,
    googleReviews: 345,
    socialMedia: { instagram: "@trattoria_sole_winti", facebook: "trattoriadelsole", followers: 2800 },
    status: "ANGESCHRIEBEN",
    score: 80,
    analysis: { websiteQuality: "gut", socialPresence: "mittel", seoScore: 69, loadTime: 1.9, mobileOptimized: true, hasOnlineBooking: false },
    recommendations: [
      "Online-Reservierung implementieren",
      "Food-Fotografie professionalisieren",
      "Wöchentliche Specials auf Instagram",
    ],
    websiteScore: 68,
    socialScore: 60,
    seoScore: 69,
    potentialValue: "CHF 1'000/Mt",
    searchBatch: "batch-2026-05-19",
    analyzedAt: "2026-05-19T13:00:00.000Z",
    createdAt: "2026-05-19T09:00:00.000Z",
    updatedAt: "2026-05-21T10:00:00.000Z",
  },
  {
    id: "demo-lead-22",
    name: "Immobilienverwaltung Seeland",
    industry: "Immobilien",
    website: "https://immo-seeland.ch",
    phone: "+41 32 123 45 67",
    email: "verwaltung@immo-seeland.ch",
    address: "Nidaugasse 18",
    city: "Biel",
    zip: "2502",
    canton: "BE",
    googlePlaceId: "ChIJ_demo_22",
    googleRating: 3.6,
    googleReviews: 22,
    socialMedia: { linkedin: "immo-seeland", followers: 310 },
    status: "ABGELEHNT",
    score: 42,
    analysis: { websiteQuality: "schwach", socialPresence: "schwach", seoScore: 35, loadTime: 4.1, mobileOptimized: false, hasOnlineBooking: false },
    recommendations: [
      "Kompletter Website-Relaunch empfohlen",
      "Social-Media-Präsenz aufbauen",
      "Google My Business Profil optimieren",
    ],
    websiteScore: 30,
    socialScore: 18,
    seoScore: 35,
    potentialValue: "CHF 1'800/Mt",
    searchBatch: "batch-2026-05-17",
    analyzedAt: "2026-05-17T14:00:00.000Z",
    createdAt: "2026-05-17T09:00:00.000Z",
    updatedAt: "2026-05-21T15:00:00.000Z",
  },
  {
    id: "demo-lead-23",
    name: "Coding Bootcamp Zürich",
    industry: "Bildung",
    website: "https://coding-bootcamp-zh.ch",
    phone: "+41 44 234 56 78",
    email: "apply@coding-bootcamp-zh.ch",
    address: "Geroldstrasse 31",
    city: "Zürich",
    zip: "8005",
    canton: "ZH",
    googlePlaceId: "ChIJ_demo_23",
    googleRating: 4.7,
    googleReviews: 98,
    socialMedia: { instagram: "@codingbootcamp_zh", linkedin: "coding-bootcamp-zurich", twitter: "@cbc_zurich", followers: 8500 },
    status: "RECHERCHIERT",
    score: 95,
    analysis: { websiteQuality: "sehr gut", socialPresence: "sehr stark", seoScore: 91, loadTime: 0.8, mobileOptimized: true, hasOnlineBooking: true },
    recommendations: [
      "Alumni-Netzwerk als Marketing-Kanal nutzen",
      "Podcast über Tech-Karrieren starten",
      "Partnerschaften mit Unternehmen ausbauen",
    ],
    websiteScore: 93,
    socialScore: 90,
    seoScore: 91,
    potentialValue: "CHF 3'500/Mt",
    searchBatch: "batch-2026-05-19",
    analyzedAt: "2026-05-19T11:00:00.000Z",
    createdAt: "2026-05-19T09:00:00.000Z",
    updatedAt: "2026-05-19T11:00:00.000Z",
  },
  {
    id: "demo-lead-24",
    name: "Gärtnerei Blütenzauber",
    industry: "Handwerk",
    website: "https://bluetenzauber.ch",
    phone: "+41 31 345 67 89",
    email: "blumen@bluetenzauber.ch",
    address: "Könizstrasse 77",
    city: "Bern",
    zip: "3008",
    canton: "BE",
    googlePlaceId: "ChIJ_demo_24",
    googleRating: 4.8,
    googleReviews: 156,
    socialMedia: { instagram: "@bluetenzauber_bern", facebook: "bluetenzauber", followers: 4200 },
    status: "NEU",
    score: 73,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
  {
    id: "demo-lead-25",
    name: "Sportcenter Rheinfelden",
    industry: "Fitness",
    website: "https://sportcenter-rheinfelden.ch",
    phone: "+41 61 456 78 90",
    email: "info@sportcenter-rheinfelden.ch",
    address: "Bahnhofstrasse 5",
    city: "Basel",
    zip: "4310",
    canton: "BS",
    googlePlaceId: "ChIJ_demo_25",
    googleRating: 3.2,
    googleReviews: 45,
    socialMedia: { facebook: "sportcenterrheinfelden", followers: 670 },
    status: "NEU",
    score: 35,
    analysis: null,
    recommendations: null,
    websiteScore: null,
    socialScore: null,
    seoScore: null,
    potentialValue: null,
    searchBatch: "batch-2026-05-22",
    analyzedAt: null,
    createdAt: "2026-05-22T06:00:00.000Z",
    updatedAt: "2026-05-22T06:00:00.000Z",
  },
]

export async function GET(request: NextRequest) {
  const session = await auth()
  if (session?.user?.globalRole !== "SUPER_ADMIN") {
    return Response.json({ error: "Nicht autorisiert" }, { status: 403 })
  }

  const searchParams = request.nextUrl.searchParams
  const status = searchParams.get("status")
  const industry = searchParams.get("industry")
  const minScore = searchParams.get("minScore")
  const maxScore = searchParams.get("maxScore")
  const search = searchParams.get("search")
  const limit = parseInt(searchParams.get("limit") || "50", 10)
  const offset = parseInt(searchParams.get("offset") || "0", 10)

  if (!prisma) {
    let filtered = [...DEMO_LEADS]
    if (status) filtered = filtered.filter((l) => l.status === status)
    if (industry) filtered = filtered.filter((l) => l.industry === industry)
    if (minScore) filtered = filtered.filter((l) => (l.score ?? 0) >= parseInt(minScore, 10))
    if (maxScore) filtered = filtered.filter((l) => (l.score ?? 0) <= parseInt(maxScore, 10))
    if (search) {
      const q = search.toLowerCase()
      filtered = filtered.filter(
        (l) =>
          l.name.toLowerCase().includes(q) ||
          l.industry.toLowerCase().includes(q) ||
          l.city?.toLowerCase().includes(q)
      )
    }
    filtered.sort((a, b) => (b.score ?? 0) - (a.score ?? 0))
    return Response.json(filtered.slice(offset, offset + limit))
  }

  try {
    const where: Record<string, unknown> = {}
    if (status) where.status = status
    if (industry) where.industry = industry
    if (minScore || maxScore) {
      where.score = {}
      if (minScore) (where.score as Record<string, number>).gte = parseInt(minScore, 10)
      if (maxScore) (where.score as Record<string, number>).lte = parseInt(maxScore, 10)
    }
    if (search) {
      where.OR = [
        { name: { contains: search, mode: "insensitive" } },
        { industry: { contains: search, mode: "insensitive" } },
        { city: { contains: search, mode: "insensitive" } },
      ]
    }

    const leads = await prisma!.lead.findMany({
      where,
      orderBy: { score: "desc" },
      take: limit,
      skip: offset,
    })

    return Response.json(leads)
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Unbekannter Fehler"
    return Response.json({ error: message }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  const session = await auth()
  if (session?.user?.globalRole !== "SUPER_ADMIN") {
    return Response.json({ error: "Nicht autorisiert" }, { status: 403 })
  }

  const body = await request.json()

  if (!body.name || !body.industry) {
    return Response.json(
      { error: "Name und Branche sind erforderlich" },
      { status: 400 }
    )
  }

  if (!prisma) {
    const demoLead = {
      id: `demo-lead-manual-${Date.now()}`,
      name: body.name,
      industry: body.industry,
      website: body.website || null,
      phone: body.phone || null,
      email: body.email || null,
      city: body.city || null,
      address: null,
      zip: null,
      canton: null,
      googlePlaceId: null,
      googleRating: null,
      googleReviews: null,
      socialMedia: null,
      status: "NEU",
      score: null,
      analysis: null,
      recommendations: null,
      websiteScore: null,
      socialScore: null,
      seoScore: null,
      potentialValue: null,
      searchBatch: null,
      analyzedAt: null,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
    return Response.json(demoLead, { status: 201 })
  }

  try {
    const lead = await prisma!.lead.create({
      data: {
        name: body.name,
        industry: body.industry,
        website: body.website || null,
        phone: body.phone || null,
        email: body.email || null,
        city: body.city || null,
      },
    })

    return Response.json(lead, { status: 201 })
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Unbekannter Fehler"
    return Response.json({ error: message }, { status: 500 })
  }
}
